### PR TITLE
Updates for Gateway 0.10.

### PR DESCRIPTION
**Pull request by mrstegeman**

### CODE REVIEW

**Comment by tomasy** [comment]
@mrstegeman Just for understanding. Is this pull request required for Gateway 0.10?
(My gateway is updated and is restarting the whole time)

**Comment by mrstegeman** [comment]
It's not required for 0.10, but will be for future versions.

**Comment by mrstegeman** [comment]
As for your gateway restarting, there seems to be an issue with the OTA where the gateway-addon library didn't always get updated. Can you try the following:

```sh
sudo pip3 install -U "git+https://github.com/mozilla-iot/gateway-addon-python@v0.10.0#egg=gateway_addon"
sudo systemctl restart mozilla-iot-gateway
```

**Comment by mrstegeman** [comment]
I'm planning to drop `package.json` support soon, so this add-on will stop working without this PR. Would you mind merging and releasing a new version?

**Comment by mrstegeman** [comment]
Just a heads up, version 0.12 of the gateway will no longer have `package.json` support, so this will stop working in 6 weeks when it's released, unless updated.

**Comment by tomasy** [comment]
> Just a heads up, version 0.12 of the gateway will no longer have `package.json` support, so this will stop working in 6 weeks when it's released, unless updated.

Do you have some link that describe what shall be used instead of `package.json`? In the examples `package.json` still exist.

**Comment by tomasy** [comment]
> > Just a heads up, version 0.12 of the gateway will no longer have `package.json` support, so this will stop working in 6 weeks when it's released, unless updated.
> 
> Do you have some link that describe what shall be used instead of `package.json`? In the examples `package.json` still exist.

Sorry, I was to fast. I did not saw that this was a pull request.

**Comment by mrstegeman** [comment]
The new format is described here: https://github.com/mozilla-iot/addon-list/blob/master/manifest.md

**Comment by mrstegeman** [comment]
Also, we keep `package.json` around for gateways that are not running 0.10+. It’s not strictly necessary.

**Comment by mrstegeman** [comment]
Thanks for pulling the changes in!

**Comment by tomasy** [comment]
@mrstegeman Just one more question. I had one more adapter in the past (Zigbee Conbee adapter). When I started to update it too I discovered it was removed by you with the commit comment
_It is incredibly confusing and the maintainer is unresponsive._
I do not understand what is confusing and in what way I was "unresponsive"? I have no unanswered message from you. And... if you want to remove an adapter please notify the owner!!

**Comment by mrstegeman** [comment]
I had opened a [PR](https://github.com/tomasy/zigbee-conbee-adapter/pull/10) and an [issue](https://github.com/tomasy/zigbee-conbee-adapter/issues/12) and never got a response, after several months. The naming was confusing a lot of users, given that our official Zigbee adapter supports the Conbee dongles.

**Comment by mrstegeman** [comment]
With that said, I'm happy to re-add it if we can figure out a way to make the name and description more clear.

**Comment by tomasy** [comment]
Sorry, I apologize, my fault. 
I now discovered that the last mail I received from the project zigbee-conbee-adapter was from 2018-12-28. I had to check the setting. I receive mail from date-time-adapter but not from the other one

**Pull request closed without merging**
